(function(g){var window=this;'use strict';var Z5b=function(F,J,b){g.S(function(I){F.C=g.E6(J,b);g.N4(I)})},vZ=function(F){F.isActive()||F.start()},H5W=function(F,J){return J?F.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Lkb=function(F){return g.hP(F)||F.S("web_enable_caption_language_preference_stickiness")},FDV=function(F,J){var b=new g.qF;
b.languageCode=F.languageCode;b.languageName=F.languageName;b.name=F.name;b.displayName=F.displayName;b.kind=F.kind;b.isDefault=!1;b.C=F.C;b.isTranslateable=F.isTranslateable;b.vssId=F.vssId;b.url=F.url;b.translationLanguage=J;F.xtags&&(b.xtags=F.xtags);F.captionId&&(b.captionId=F.captionId);return b},JDm=function(F,J){var b,I,u;
return g.S(function(w){if(w.C==1)return b=F+"|"+J,g.T(w,g.tY(),2);if(w.C!=3){I=w.U;if(!I)throw g.NP("gct");return g.T(w,g.Gt(I),3)}u=w.U;return w.return(u.get("captions",b))})},b$b=function(F,J,b){JDm(F,J).then(function(I){I&&b(I.trackData,new g.qF(I.metadata))})},w1R=function(F){if(!I8U.test(F))throw Error("'"+F+"' is not a valid hex color");
F.length==4&&(F=F.replace(ulb,"#$1$1$2$2$3$3"));F=F.toLowerCase();F=parseInt(F.slice(1),16);return[F>>16,F>>8&255,F&255]},Mqt=function(){var F=void 0;
F=F===void 0?{}:F;var J="suggest_correction"in g.PV1?g.PV1.suggest_correction:"Edit caption";J=J||"";var b={},I;for(I in F){b={ON:b.ON};b.ON=I;var u=function(w){return function(){return String(F[w.ON])}}(b);
J=J.replace(new RegExp("\\$\\{"+b.ON+"\\}","gi"),u);J=J.replace(new RegExp("\\$"+b.ON,"gi"),u)}return J},ADb=function(){return g.S9("yt-player-caption-display-settings")},aC=function(){this.segments=[]},qam=function(F,J){var b=g.AL(F.segments,J);
b>=0||b<0&&(-b-1)%2===1||(b=-b-1,b>0&&J-F.segments[b-1]===1&&b<F.segments.length&&F.segments[b]-J===1?(g.ZH(F.segments,b),g.ZH(F.segments,b-1)):b>0&&J-F.segments[b-1]===1?F.segments[b-1]=J:b<F.segments.length&&F.segments[b]-J===1?F.segments[b]=J:(g.wy(F.segments,b,0,J),g.wy(F.segments,b+1,0,J)))},vMR=function(F,J,b,I,u,w){g.R.call(this);
this.policy=F;this.player=J;this.Tj=b;this.Y=I;this.D=u;this.N=w;this.Z=new aC;this.W=-1;this.T=this.U=this.C=null;this.eE=0;this.V=new g.ty(this.DI,1E3,this);this.events=new g.s5(this);g.k(this,this.V);g.k(this,this.events);this.events.B(J,"SEEK_COMPLETE",this.hI);this.hI();this.DI()},a8L=function(F){return F.C&&F.C.H1?F.C.H1+F.player.Xq()<F.player.getCurrentTime():!1},e68=function(F,J){if(F.policy.qa&&F.player.f1()){var b=g.Co(J,F.policy,{});
b.set("pot",F.player.f1());b=b.tF()}else b=g.Co(J,F.policy,{}).tF();var I={format:"RAW",withCredentials:!0};if(F.policy.fW){I.method="POST";var u=J.Z;u&&Object.keys(u).length>0?I.postBody=g.ux(u,g.Ur):I.postBody=(0,g.gg)([120,0])}F.D&&(I.responseType="arraybuffer");var w=++F.eE,M=(0,g.jR)();F.T=g.Px(b,I,3,100).then(function(q){if(F.policy.ws&&w%100===1){var v=(0,g.jR)();F.player.UQ("caprsp",{rn:w,ms:v-M,kb:(q.xhr.responseText.length/1024).toFixed()})}a:{q=q.xhr;F.iR();if(F.U){var a=!(F.D?q.response:
q.responseText)||q.status>=400;if(v=g.jl3(q)){q=g.Co(F.U,F.policy,{});F.U.Vz(q,v);e68(F,F.U);break a}a?F.player.UQ("capfail",{status:q.status}):(F.player.Iu().QJ("fcb_r"),v=F.U.aI[0].Mf,F.Y!=null&&F.W!==v&&(a=F.U.aI[0],F.D?F.Y(q.response,(a.startTime+F.player.Xq())*1E3):F.Y(q.responseText,(a.startTime+F.player.Xq())*1E3),F.W=v))}F.U=null;F.T=null}}).rX(function(q){F.U=null;
F.T=null;var v;F.player.UQ("capfail",{rn:w,status:(v=q.xhr)==null?void 0:v.status})});
F.U=J;qam(F.Z,F.U.aI[0].Mf)},ex=function(F,J){g.PU.call(this,J);
this.C=F;this.G=J;this.T=null;this.W=!1;this.logger=new g.Hl("caps");this.V=g.dX(this.G.J())&&!this.C.isManifestless},p18=function(F,J){var b=[],I;
for(I in F.C.C)if(F.C.C.hasOwnProperty(I)){var u=F.C.C[I];if(g.TN(u,J||null)){var w=u.info.id,M=w,q="."+w,v="",a="";if(u=u.info.captionTrack)w=u.languageCode,M=u.displayName,q=u.vssId,v=u.kind,a=u.id;else{u=w;var e=g.HIR.get(u);e==null&&(e=KDH[u]||KDH[u.replace(/-/g,"_")],g.HIR.set(u,e));u=e;M=u||M}b.push(new g.qF({id:I,languageCode:w,languageName:M,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:v,captionId:a}))}}return b},gMW=function(F,J){return J!=null&&J in F.C.C?F.C.C[J]:null},
mDb=function(F,J,b){var I=[],u;
for(u in F.C.C)if(F.C.C.hasOwnProperty(u)){var w=F.C.C[u];if(g.TN(w,b||null)){var M=w.info.captionTrack;M&&M.languageCode===J&&I.push(w)}}return I.length?I[0]:null},KZ=function(F,J,b,I,u,w,M,q,v,a){var e=a.isInline()&&!0,K={};
Object.assign(K,J);Object.assign(K,F.params);Object.assign(K,b);var p={};Object.assign(p,J.kH);F.params.kH&&Object.assign(p,F.params.kH);Object.assign(p,b.kH);e&&(K.windowOpacity=.6,p.backgroundOpacity=0);K.kH=p;var m=K.CF===1,y=[{X:"span",K:"captions-text",L:{style:"word-wrap: normal; display: block;"}}],f,d,G;(q=q.pW("caption_edit_on_hover")&&((f=a.getVideoData().getPlayerResponse())==null?void 0:(d=f.captions)==null?void 0:(G=d.playerCaptionsTracklistRenderer)==null?void 0:G.openTranscriptCommand))&&
y.unshift({X:"button",K:"caption-edit",L:{tabindex:"0","aria-label":Mqt()},j:[{X:"svg",L:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{X:"path",L:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.U.call(this,{X:"div",K:"caption-window",L:{id:"caption-window-"+F.id,dir:m?"rtl":"ltr",tabindex:"0",lang:K.lang},j:y});var P=
this;this.V=[];this.WN=!1;this.U=F;this.qf=this.fW=null;this.playerWidth=w;this.playerHeight=M;this.Y=null;this.maxWidth=w*.96;this.maxHeight=M*.96;this.C=K;this.If=b;this.eE=J;this.Z=this.RI("captions-text");this.xm=this.Z.style.getPropertyValue("box-decoration-break")!==""||this.Z.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.zj=yDz(I,u,w,M);this.NW=v;q&&(this.W=this.RI("caption-edit"),this.B(this.W,"click",function(){P.NW()}));
this.type=0;this.Jz=this.zj*i$R(p);this.Um=e;F=new g.L1(this.element,!0);g.k(this,F);F.subscribe("dragstart",this.HT,this);F.subscribe("dragmove",this.Sr,this);F.subscribe("dragend",this.Qy,this);this.nW=this.oI=this.cN=this.bR=0;F="";this.C.windowOpacity&&(F=w1R(this.C.windowColor),F="rgba("+F[0]+","+F[1]+","+F[2]+","+this.C.windowOpacity+")");J={"background-color":F,display:this.C.isVisible===!1?"none":"","text-align":z61[this.C.textAlign]};this.xm&&(J["border-radius"]=F?this.Jz/8+"px":"");(this.T=
this.U.params.CF===2||this.U.params.CF===3)&&Nlb(this,this.element);g.aN(this.element,J);if(e){var r;(r=this.element.parentElement)==null||r.style.setProperty("--caption-window-color",F)}switch(this.C.qQ){case 0:case 1:case 2:g.uG(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.uG(this.element,"ytp-caption-window-bottom")}},Nlb=function(F,J){var b="vertical-rl";
F.C.cA===1&&(b="vertical-lr");g.K6&&(b=b==="vertical-lr"?"tb-lr":"tb-rl");g.aN(J,"-o-writing-mode",b);g.aN(J,"-webkit-writing-mode",b);g.aN(J,"writing-mode",b);g.aN(J,"text-orientation","upright");g.uG(J,"ytp-vertical-caption");F.U.params.CF===3&&(g.aN(J,"text-orientation",""),g.aN(J,"transform","rotate(180deg)"))},i$R=function(F){var J=1+.25*(F.fontSizeIncrement||0);
if(F.offset===0||F.offset===2)J*=.8;return J},l8z=function(F,J){var b={},I=J.background?J.background:F.C.kH.background;
if(J.backgroundOpacity!=null||J.background){var u=J.backgroundOpacity!=null?J.backgroundOpacity:F.C.kH.backgroundOpacity;I=w1R(I);b.background="rgba("+I[0]+","+I[1]+","+I[2]+","+u+")";F.xm&&(b["box-decoration-break"]="clone",b["border-radius"]=F.Jz/8+"px")}if(J.fontSizeIncrement!=null||J.offset!=null)b["font-size"]=F.zj*i$R(J)+"px";I=1;u=J.color||F.C.kH.color;if(J.color||J.textOpacity!=null)u=w1R(u),I=J.textOpacity==null?F.C.kH.textOpacity:J.textOpacity,u="rgba("+u[0]+","+u[1]+","+u[2]+","+I+")",
b.color=u,b.fill=u;var w=J.charEdgeStyle;w===0&&(w=void 0);if(w){u="rgba(34, 34, 34, "+I+")";var M="rgba(204, 204, 204, "+I+")";J.QI&&(M=u=J.QI);var q=F.zj/16/2,v=Math.max(q,1),a=Math.max(2*q,1),e=Math.max(3*q,1),K=Math.max(5*q,1);I=[];switch(w){case 4:for(;e<=K;e+=q)I.push(a+"px "+a+"px "+e+"px "+u);break;case 1:a=window.devicePixelRatio>=2?.5:1;for(w=v;w<=e;w+=a)I.push(w+"px "+w+"px "+u);break;case 2:I.push(v+"px "+v+"px "+M);I.push("-"+v+"px -"+v+"px "+u);break;case 3:for(e=0;e<5;e++)I.push("0 0 "+
a+"px "+u)}b["text-shadow"]=I.join(", ")}u="";switch(J.fontFamily){case 1:u='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:u='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:u='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:u='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:u='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:u=g.O6()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:u='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}u&&(b["font-family"]=u);u=J.offset;u==null&&(u=F.C.kH.offset);switch(u){case 0:b["vertical-align"]="sub";break;case 2:b["vertical-align"]="super"}J.fontFamily===7&&(b["font-variant"]="small-caps");J.bold&&(b["font-weight"]="bold");J.italic&&(b["font-style"]="italic");J.underline&&(b["text-decoration"]=
"underline");J.dfQ&&(b.visibility="hidden");J.Qn===1&&F.T&&(b["text-combine-upright"]="all",b["text-orientation"]="mixed",u=g.x2||g.ia,F.U.params.CF===3?b.transform=u?"rotate(90deg)":"rotate(180deg)":u&&(b.transform="rotate(-90deg)"));if(J.H5===1||J.H5===2||J.H5===3||J.H5===4||J.H5===5)if(g.x2)b["font-weight"]="bold";else switch(b["text-emphasis-style"]="filled circle",b["text-emphasis-color"]="currentcolor",b["webkit-text-emphasis"]="filled circle",J.H5){case 4:case 3:b["text-emphasis-position"]=
"under left";b["webkit-text-emphasis-position"]="under left";break;case 5:case 2:b["text-emphasis-position"]="over right",b["webkit-text-emphasis-position"]="over right"}return b},pZ=function(F){F=F.split("px");
return F.length>0?(F=Number(F[0]))?F:0:0},f8b=function(F){F.Y=g.H1("SPAN");
g.aN(F.Y,{display:"block"});g.uG(F.Y,"caption-visual-line");F.Z.appendChild(F.Y)},WDb=function(F,J){var b=g.H1("SPAN");
g.aN(b,{display:"inline-block","white-space":"pre-wrap"});g.aN(b,l8z(F,J));b.classList.add("ytp-caption-segment");F.Y.appendChild(b);b.previousElementSibling&&(g.aN(b.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.aN(b,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return b},dDV=function(F,J,b){F.WN=F.WN||!!b;
var I={};Object.assign(I,F.C.kH);Object.assign(I,b||J.C);Object.assign(I,F.If.kH);(b=!F.Y)&&f8b(F);for(var u=F.fW&&F.qf&&g.B1(I,F.qf)?F.fW:WDb(F,I),w=typeof J.text==="string",M=w?J.text.split("\n"):[J.text],q=0;q<M.length;q++){var v=q>0||!J.append,a=M[q];v&&!b?(f8b(F),u=WDb(F,I)):v&&b&&(b=!1);a&&(u.appendChild(w?g.L$(a):a),w||a.tagName!=="RUBY"||a.childElementCount!==4||g.x2||!g.KL(a.children[2],"text-emphasis")||(v=F.T?"padding-right":"padding-top",g.KL(a.children[2],"text-emphasis-position")&&(v=
F.T?"padding-left":"padding-bottom"),g.xM?g.aN(u,v,"1em"):g.aN(u,v,"0.5em")))}F.qf=I;F.fW=u;F.V.push(J)},yDz=function(F,J,b,I){var u=J/360*16;
J>=F&&(F=640,I>b*1.3&&(F=480),u=b/F*16);return u},jf1=function(){this.T=this.time=this.mode=this.U=0;
this.Z=new EMt(this);this.D=new EMt(this);this.C=[];this.clear()},Vqt=function(F,J,b){if(F===255&&J===255||!F&&!J)return{Wm:F,
QQ:J,result:0};F=Got[F];J=Got[J];if(F&128){var I;if(I=!(J&128))I=J,I=b.o8()&&b.QQ===I;if(I)return{Wm:F,QQ:J,result:1}}else if(J&128&&1<=F&&F<=31)return{Wm:F,QQ:J,result:2};return{Wm:F,QQ:J,result:3}},BlH=function(F,J,b,I){J===255&&b===255||!J&&!b?(++F.T===45&&F.reset(),F.Z.U.clear(),F.D.U.clear()):(F.T=0,Pet(F.Z,J,b,I))},Tle=function(F,J){F.C.sort(function(u,w){var M=u.time-w.time;
return M===0?u.order-w.order:M});
for(var b=g.N(F.C),I=b.next();!I.done;I=b.next())I=I.value,F.time=I.time,I.type===0?BlH(F,I.O$,I.Dx,J):I.type===1&&F.U&496&&Pet(F.D,I.O$,I.Dx,J);F.C.length=0},gp=function(){this.type=0},mn=function(){this.state=this.QQ=this.Wm=0},rDk=function(){this.timestamp=this.C=0},yV=function(F){this.D=F;
this.T=[];this.C=this.U=this.row=0;this.style=new gp;for(F=this.Z=0;F<=15;F++){this.T[F]=[];for(var J=0;J<=32;J++)this.T[F][J]=new rDk}},iN=function(F,J){if(F.style.type===3){for(var b=0,I=0,u=F.D.time+0,w="",M="",q=u,v=1;v<=15;++v){for(var a=!1,e=I?I:1;e<=32;++e){var K=F.T[v][e];
if(K.C!==0){b===0&&(b=v,I=e);a=String.fromCharCode(K.C);var p=K.timestamp;p<u&&(u=p);K.timestamp=q;M&&(w+=M,M="");w+=a;a=!0}if((K.C===0||e===32)&&a){M="\n";break}else if(I&&!a)break}if(b&&!a)break}w&&J.Z(b,I,u,q,w)}else for(I=b=0,w=u=F.D.time+0,M=1;M<=15;++M)for(q="",v=1;v<=32;++v)if(e=F.T[M][v],K=e.C,K!==0&&(b===0&&(b=M,I=v),a=String.fromCharCode(K),p=e.timestamp,p<=u&&(u=p),q+=a,e.reset()),v===32||K===0)q&&J.Z(b,I,u,w,q),u=w,q="",I=b=0},Cem=function(F,J){switch(F){case 0:return Sat[(J&127)-32];
case 1:return sfL[J&15];case 2:return Yam[J&31];case 3:return $DH[J&31]}return 0},zQ=function(F){return F.T[F.row][F.U]},NT=function(F,J,b){J>=2&&F.U>1&&(--F.U,zQ(F).C=0);
var I=zQ(F);I.timestamp=F.D.time+0;I.C=Cem(J,b);F.U<32&&F.U++},X18=function(F,J,b,I){for(var u=0;u<I;u++)for(var w=0;w<=32;w++){var M=F.T[J+u][w],q=F.T[b+u][w];
M.C=q.C;M.timestamp=q.timestamp}},lN=function(F,J,b){for(var I=0;I<b;I++)for(var u=0;u<=32;u++)F.T[J+I][u].reset()},QfH=function(F){F.row=F.C>0?F.C:1;
F.U=1;lN(F,0,15)},R6W=function(F){this.T=F;
this.D=0;this.style=new gp;this.W=new yV(this.T);this.V=new yV(this.T);this.text=new yV(this.T);this.U=this.W;this.Z=this.V;this.C=this.U},DDk=function(F,J,b){var I=F.U,u=!1;
switch(F.style.get()){case 4:case 1:case 2:F.style.get()===4&&I.C>0||(iN(I,b),QfH(F.U),QfH(F.Z),I.row=15,I.C=J,u=!0)}F.style.set(3);F.C=I;F.C.style=F.style;F.T.mode=1<<I.Z;u?I.U=1:I.C!==J&&(I.C>J?(iN(I,b),lN(I,I.row-I.C,J)):I.row<J&&(J=I.C),I.C=J)},ko5=function(F){F.style.set(1);
F.C=F.Z;F.C.C=0;F.C.style=F.style;F.T.mode=1<<F.C.Z},O$8=function(F){F.style.set(4);
F.C=F.text;F.C.style=F.style;F.T.mode=1<<F.C.Z},EMt=function(F){this.C=F;
this.D=0;this.T=new R6W(this.C);this.W=new R6W(this.C);this.U=new mn;this.Z=this.T},Pet=function(F,J,b,I){F.U.update();
J=Vqt(J,b,F.U);switch(J.result){case 0:return;case 1:case 2:return}var u=J.Wm;b=J.QQ;if(32<=u||!u)F.C.mode&F.C.U&&(J=u,J&128&&(J=127),b&128&&(b=127),F=F.Z.C,J&96&&NT(F,0,J),b&96&&NT(F,0,b),J!==0&&b!==0&&F.style.type===3&&iN(F,I));else if(u&16)a:if(!F.U.matches(u,b)&&(J=F.U,J.Wm=u,J.QQ=b,J.state=2,J=u&8?F.W:F.T,F.Z=J,F.C.mode=1<<(F.D<<2)+(J.D<<1)+(J.style.type===4?1:0),(F.C.mode|1<<(F.D<<2)+(J.D<<1)+(J.style.type!==4?1:0))&F.C.U))if(b&64){I=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(u&7)<<1|b>>5&1];
F=b&16?((b&14)>>1)*4:0;b=J.C;switch(J.style.get()){case 4:I=b.row;break;case 3:if(I!==b.row){if(I<b.C&&(I=b.C,I===b.row))break;var w=1+b.row-b.C,M=1+I-b.C;X18(b,M,w,b.C);J=w;u=b.C;M<w?(w=M+u-w,w>0&&(J+=w,u-=w)):(w=w+u-M,w>0&&(u-=w));lN(b,J,u)}}b.row=I;b.U=F+1}else switch(u&7){case 1:switch(b&112){case 32:NT(J.C,0,32);break a;case 48:b===57?(I=J.C,zQ(I).C=0,I.U<32&&I.U++):NT(J.C,1,b&15)}break;case 2:b&32&&NT(J.C,2,b&31);break;case 3:b&32&&NT(J.C,3,b&31);break;case 4:case 5:if(32<=b&&b<=47)switch(b){case 32:ko5(J);
break;case 33:I=J.C;I.U>1&&(--I.U,zQ(I).C=0);break;case 36:I=J.C;J=zQ(I);for(F=0;F<=15;F++)for(b=0;b<=32;b++)if(I.T[F][b]===J){for(;b<=32;b++)I.T[F][b].reset();break}break;case 37:DDk(J,2,I);break;case 38:DDk(J,3,I);break;case 39:DDk(J,4,I);break;case 40:NT(J.C,0,32);break;case 41:J.style.set(2);J.C=J.U;J.C.C=0;J.C.style=J.style;J.T.mode=1<<J.C.Z;break;case 42:I=J.text;I.C=15;I.style.set(4);QfH(I);O$8(J);break;case 43:O$8(J);break;case 44:F=J.U;switch(J.style.get()){case 1:case 2:case 3:iN(F,I)}lN(F,
0,15);break;case 45:b:{F=J.C;switch(J.style.get()){default:case 2:case 1:break b;case 4:if(F.row<15){++F.row;F.U=1;break b}break;case 3:}F.C<2&&(F.C=2,F.row<F.C&&(F.row=F.C));J=F.row-F.C+1;iN(F,I);X18(F,J,J+1,F.C-1);lN(F,F.row,1)}break;case 46:lN(J.Z,0,15);break;case 47:iN(J.U,I),J.Z.updateTime(J.T.time+0),I=J.Z,J.Z=J.U,J.U=I,ko5(J)}break;case 7:switch(b){case 33:case 34:case 35:I=J.C,(I.U+=b&3)>32&&(I.U=32)}}},oMb=function(){},fZ=function(F,J,b,I,u,w,M){w=w===void 0?!1:w;
M=M===void 0?null:M;g.b6.call(this,F,F+J,{priority:b,namespace:"captions"});this.windowId=I;this.text=u;this.append=w;this.C=M},cD1=function(F,J,b,I,u,w,M){var q=w[0],v=M[q.getAttribute("p")];
if(v.Eo===1){var a=w[1],e=w[2];w=w[3];q.getAttribute("t");a.getAttribute("t");e.getAttribute("t");w.getAttribute("t");q.getAttribute("p");a.getAttribute("p");w.getAttribute("p");M=M[e.getAttribute("p")];q=h6W(q.textContent,a.textContent,e.textContent,w.textContent,M);return new fZ(F,J,u,b,q,I,v)}switch(v.Eo){case 9:case 10:v.H5=1;break;case 11:v.H5=2;break;case 12:v.H5=3;break;case 13:v.H5=4;break;case 14:v.H5=5}return new fZ(F,J,u,b,q.textContent||"",I,v)},h6W=function(F,J,b,I,u){var w=g.O6(),M=
w?g.H1("DIV"):g.H1("RUBY"),q=g.H1("SPAN");
q.textContent=F;M.appendChild(q);F=w?g.H1("DIV"):g.H1("RP");F.textContent=J;M.appendChild(F);J=w?g.H1("DIV"):g.H1("RT");J.textContent=b;M.appendChild(J);b=u.Eo;if(b===10||b===11||b===12||b===13||b===14)if(g.aN(J,"text-emphasis-style","filled circle"),g.aN(J,"text-emphasis-color","currentcolor"),g.aN(J,"webkit-text-emphasis","filled circle"),u.Eo===11||u.Eo===13)g.aN(J,"webkit-text-emphasis-position","under left"),g.aN(J,"text-emphasis-position","under left");b=!0;if(u.Eo===4||u.Eo===7||u.Eo===12||
u.Eo===14)g.aN(M,"ruby-position","over"),g.aN(M,"-webkit-ruby-position","before");else if(u.Eo===5||u.Eo===6||u.Eo===11||u.Eo===13)g.aN(M,"ruby-position","under"),g.aN(M,"-webkit-ruby-position","after"),b=!1;u=w?g.H1("DIV"):g.H1("RP");u.textContent=I;M.appendChild(u);w&&(I=b,g.aN(M,{display:"inline-block",position:"relative"}),w=M.firstElementChild.nextElementSibling,g.aN(w,"display","none"),w=w.nextElementSibling,g.aN(w,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.aN(M.lastElementChild,"display","none"),I?(g.aN(M,"padding-top","0.6em"),g.aN(w,"top","0")):(g.aN(M,"padding-bottom","0.6em"),g.aN(w,"bottom","0")));return M},WZ=function(){g.R.apply(this,arguments)},dp=function(F,J,b,I,u){g.b6.call(this,F,F+J,{priority:b,
namespace:"captions"});this.id=I;this.params=u;this.C=[]},UDL=function(F){var J="_"+EM++;
return new dp(0,0x8000000000000,0,J,F)},jx=function(F){WZ.call(this);
this.T=F;this.pens={};this.V={};this.Y={};this.Z="_"+EM++;this.W={};this.U=this.C=null;this.D=!0},GQ=function(F,J){F=F.getAttribute(J);
if(F!=null)return Number(F)},VV=function(F,J){F=F.getAttribute(J);
if(F!=null)return F==="1"},PZ=function(F,J){F=GQ(F,J);
return F!==void 0?F:null},TQ=function(F,J){F=F.getAttribute(J);
if(F!=null)return BZ.test(F),F},xDk=function(F,J){var b={},I=J.getAttribute("ws");
Object.assign(b,I?F.Y[I]:F.T);F=PZ(J,"mh");F!=null&&(b.Dd=F);F=PZ(J,"ju");F!=null&&(b.textAlign=F);F=PZ(J,"pd");F!=null&&(b.CF=F);F=PZ(J,"sd");F!=null&&(b.cA=F);F=TQ(J,"wfc");F!=null&&(b.windowColor=F);J=GQ(J,"wfo");J!==void 0&&(b.windowOpacity=J/255);return b},nM1=function(F,J){var b={},I=J.getAttribute("wp");
I&&Object.assign(b,F.V[I]);F=PZ(J,"ap");F!=null&&(b.qQ=F);F=GQ(J,"cc");F!=null&&(b.VQ=F);F=GQ(J,"ah");F!=null&&(b.Fx=F);F=GQ(J,"rc");F!=null&&(b.pA=F);J=GQ(J,"av");J!=null&&(b.h6=J);return b},tqz=function(F,J,b,I){var u={};
Object.assign(u,nM1(F,J));Object.assign(u,xDk(F,J));I?g.B1(u,F.T)?(I=F.Z,u=F.T):I="_"+EM++:I=J.getAttribute("id")||"_"+EM++;F=GQ(J,"t")+b;J=GQ(J,"d")||0x8000000000000;if(u.CF===2||u.CF===3)b=u.pA,u.pA=u.VQ,u.VQ=b;return new dp(F,J,0,I,u)},rp=function(F){WZ.call(this);
this.D=F;this.C=new Map;this.T=new Map;this.Z=new Map;this.U=new Map},Sx=function(F){F=g.AD(Math.round(F),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-F.length)+F},Z$e=function(F,J,b,I,u){I===0&&(I=0x8000000000000);
var w={};J.wpWinPosId&&Object.assign(w,F.T.get(J.wpWinPosId));J.wsWinStyleId&&Object.assign(w,F.Z.get(J.wsWinStyleId));F=J.rcRowCount;F!==void 0&&(w.pA=F);J=J.ccColCount;J!==void 0&&(w.VQ=J);if(w.CF===2||w.CF===3)J=w.pA,w.pA=w.VQ,w.VQ=J;return new dp(b,I,0,u,w)},sM=function(F,J,b){g.PU.call(this,F);
this.videoData=J;this.audioTrack=b;this.D=J.Cu},Yx=function(F,J,b,I,u,w,M,q,v,a){KZ.call(this,F,J,b,I,u,w,M,q,v,a);
this.type=1},$x=function(F,J,b){this.trackData=F;
this.W=b;this.version=this.D=this.T=this.byteOffset=0;this.U=[];this.C=new DataView(this.trackData)},CZ=function(F){var J=F.byteOffset;
F.byteOffset+=1;return F.C.getUint8(J)},X3=function(F){var J=F.byteOffset;
F.byteOffset+=4;return F.C.getUint32(J)},QV=function(F,J){WZ.call(this);
this.U=F;this.T=J;this.track=this.T.languageName==="CC3"?4:0;this.C=new jf1;this.C.U=1<<this.track},LDk=function(F){if(typeof F==="string")return!1;
F=new $x(F,8,0);return H$b(F)},H$b=function(F){if(!(F.byteOffset<F.C.byteLength)||X3(F)!==1380139777)return!1;
F.version=CZ(F);if(F.version>1)return!1;CZ(F);CZ(F);CZ(F);return!0},RC=function(F,J,b,I,u,w,M,q,v,a){KZ.call(this,F,J,b,I,u,w,M,q,v,a);
var e=this;this.type=2;this.Gj=[];this.Tj=this.N=this.dD=0;this.kQ=NaN;this.Om=0;this.Kk=null;this.KW=new g.ty(this.d0j,433,this);this.W&&(a.createClientVe(this.W,this,167342),this.B(this.W,"click",function(){a.logClick(e.W)}),F=new g.L1(this.element,!0),g.k(this,F),F.subscribe("hoverstart",function(){a.logVisibility(e.W,!0)},this));
g.uG(this.element,"ytp-caption-window-rollup");g.k(this,this.KW);g.aN(this.element,"overflow","hidden")},FbV=function(F,J){if(!J)return"";
F.T&&F.U.params.cA!==1&&(J*=-1);return"translate"+(F.T?"X":"Y")+"("+J+"px)"},J65=function(F){F.Gj=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var J=F.U.params.pA,b=0,I=0,u=F.Gj.length-1;b<J&&u>-1;){var w=F.Gj[u];I+=F.T?w.offsetWidth:w.offsetHeight;b++;u--}F.N=I;J=Math;b=J.max;isNaN(F.kQ)&&((I=F.C.VQ)?(u=g.H1("SPAN"),g.wK(u,"\u2013".repeat(I)),g.aN(u,l8z(F,F.C.kH)),F.Z.appendChild(u),F.kQ=u.offsetWidth,F.Z.removeChild(u)):F.kQ=0);I=F.Z;F.Tj=b.call(J,F.kQ,F.Om,(F.T?I.offsetHeight:I.offsetWidth)+1)},bbk=function(F,J){J65(F);
var b=F.Gj.reduce(function(w,M){return(F.T?M.offsetWidth:M.offsetHeight)+w},0);
b=F.N-b;if(b!==F.dD){var I=b>0&&F.dD===0,u=b<F.dD;J||isNaN(b)||I||!u||(g.uG(F.element,"ytp-rollup-mode"),g.Z_(F.KW));g.aN(F.Z,"transform",FbV(F,b));F.dD=b}J65(F)},IrV=function(F,J,b,I){var u=this;
this.G=F;this.U=J;this.logger=b;this.MW=I;this.Ym=[];this.Lc=[];this.Yc=null;this.Po={tD_:function(){return u.Yc},
Z4:function(){return u.Ym}};
F=g.eB(this.G.J().experiments,"html5_override_micro_discontinuities_threshold_ms");this.C=F>0?F:10},MXR=function(F,J){F.Yc=function(b,I){if(b.info.Z){var u=b;
if(F.Lc.length>0){for(u=F.Lc.shift();F.Lc.length>0;)u=g.xm(u,F.Lc.shift());u=g.xm(u,b)}if(u){b=u;try{var w=g.no(b)*1E3}catch(a){w=b.info.startTime*1E3}try{var M=g.mtk(b)*1E3}catch(a){M=b.info.duration*1E3}if(w<0||M<0)w<0&&(w=b.info.startTime*1E3),M<0&&(M=b.info.duration*1E3);b.info.startTime=w/1E3;b.info.hF=w/1E3;b.info.duration=M/1E3;b.info.W=M/1E3;w=F.K5(u);M=w.Mf;w={formatId:w.formatId,startTimeMs:w.startTimeMs,durationMs:w.durationMs,I5:M,Tn:M};M=u9m(F.Ym,w.startTimeMs);var q=(b=M>=0?F.Ym[M]:
null)?b.startTimeMs+b.durationMs:0,v=w.startTimeMs+w.durationMs;!b||w.startTimeMs-q>F.C?F.Ym.splice(M+1,0,w):(b.durationMs=Math.max(q,v)-b.startTimeMs,b.Tn=Math.max(b.Tn,w.Tn));I(F.Ym);I=u.AF();wz5(F.U,I.buffer.slice(I.byteOffset,I.byteLength+I.byteOffset),J,u.info.hF)}else F.logger.C(350058965,"Empty slice")}else F.Lc.push(b)};
F.G.addEventListener("sabrCaptionsDataLoaded",F.Yc)},u9m=function(F,J){F=g.AL(F,{startTimeMs:J},function(b,I){return b.startTimeMs-I.startTimeMs});
return F>=0?F:-F-2},A6U=function(F,J){g.PU.call(this,J);
this.C=F;this.G=J;this.logger=new g.Hl("caps");this.T=this.W=null;this.V=new IrV(this.G,this,this.logger,this.C.MW)},wz5=function(F,J,b,I){F.logger.debug(function(){return"SABR captions data received for "+I});
F.W?F.T==null?F.logger.C(350058965,"Null loaded track meta data at captions data received"):b.b4(J,F.T,I*1E3):F.logger.C(350058965,"Null Representation at captions data received")},qP8=function(F,J){var b=[],I;
for(I in F.C.C)if(F.C.C.hasOwnProperty(I)){var u=F.C.C[I];if(g.TN(u,J||null)){var w=u.info.id,M=w,q="."+w,v="",a="";if(u=u.info.captionTrack)w=u.languageCode,M=u.displayName,q=u.vssId,v=u.kind,a=u.id;b.push(new g.qF({id:I,languageCode:w,languageName:M,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:v,captionId:a}))}}return b},ve8=function(F,J,b){var I=[],u;
for(u in F.C.C)if(F.C.C.hasOwnProperty(u)){var w=F.C.C[u];if(g.TN(w,b||null)){var M=w.info.captionTrack;M&&M.languageCode===J&&I.push(w)}}return I.length?I[0]:null},arW=function(F,J){if(!g.wNC(F)||F.C!=null&&g.dX(J.J())&&!F.C.isManifestless&&F.C.C.rawcc!=null)return!1;
J=!!F.C&&F.C.isManifestless&&Object.values(F.C.C).some(function(b){return g.TN(b,"386")});
F=!!F.C&&!F.C.isManifestless&&g.Buz(F.C);return J||F},D3=function(){WZ.call(this)},eh8=function(F,J,b,I,u,w,M,q,v){switch(M.tagName){case "b":q.bold=!0;
break;case "i":q.italic=!0;break;case "u":q.underline=!0}for(var a=0;a<M.childNodes.length;a++){var e=M.childNodes[a];if(e.nodeType===3)e=new fZ(J,b,I,u.id,e.nodeValue,w||a>0,g.Vj(q)?void 0:q),v.push(e),u.C.push(e);else{var K={};Object.assign(K,q);eh8(F,J,b,I,u,!0,e,K,v)}}},Kb1=function(F){var J=F.split(":");
F=0;J=g.N(J);for(var b=J.next();!b.done;b=J.next())F=F*60+Number(b.value);return F*1E3},pzb=function(F,J,b,I){I=Object.assign({Dd:0},I);
return new dp(F,J,b,"_"+EM++,I)},kx=function(F,J){g.R.call(this);
this.G=F;this.rD=J;this.C=null;this.U=this.G.NP();this.logger=new g.Hl("caps")},mIV=function(F,J,b){if(typeof J==="string"||LDk(J))return[{trackData:J,
y0:b}];var I=new DataView(J);if(I.byteLength<=8||I.getUint32(4)!==1718909296)return[];var u=g.dM3(I);if(F.U&&u){var w=g.mMJ(u),M=g.y17(u);u=u.fF;w&&u&&F.U.M6(u,w,M)}F=g.nk(I,1835295092);if(!F||!F.length||!F[0].size)return[];w=[];for(M=0;M<F.length;M++)u=F[M],u=new Uint8Array(J,u.dataOffset,u.size-(u.dataOffset-u.offset)),u=g.Ev(u),w.push({trackData:u,y0:b+M*1E3});geb(I,w,b);return w=w.filter(function(q){return!!q.trackData})},geb=function(F,J,b){var I=g.Rt(F,0,1836476516),u=9E4;
I&&(u=g.DT(I)||9E4);I=0;for(var w=g.nk(F,1836019558),M=0;M<w.length;M++){var q=w[M];M<J.length&&(q=g.Rt(F,q.dataOffset,1953653094))&&(q=g.Rt(F,q.dataOffset,1952867444))&&(q=g.US(q)/u*1E3,M===0&&(I=q),J[M].y0=q-I+b||b*M*1E3)}},y6k=function(F){var J={};
if(F=g.eE(F))J.lang=F,g.Mmb.test(F)&&(J.CF=1);return J},OM=function(F){g.GN.call(this,F);
var J=this;this.G=F;this.fW=[];this.Gj={};this.KW={};this.Y=!1;this.Z="NONE";this.C=this.N=this.Tj=this.zj=this.bR=null;this.Om={L8:function(){J.L8()},
b4:function(w,M,q,v){J.b4(w,M,q,v)}};
this.U=null;this.rD=this.G.J();this.videoData=this.G.getVideoData();this.cN=this.G.mG();var b;this.nW=(b=this.G.getVideoData(1))==null?void 0:g.oH(b);this.T={kH:{}};this.W={kH:{}};g.UW(this.videoData)?this.Z="OFFLINE":arW(this.videoData,this.G)?this.Z="SABR_LIVE":g.uiz(this.videoData,this.G)?this.Z="LIVE":this.videoData.captionTracks.length?this.Z="INNERTUBE":this.videoData.zU&&(this.Z="TTS");this.Jz=this.rD.controlsType==="3";this.oI=new kx(this.G,this.rD);this.kQ=new g.s5(this);this.V=new g.U({X:"div",
K:"ytp-caption-window-container",L:{id:"ytp-caption-window-container"}});this.eE={top:0,right:0,bottom:0,left:0,width:1,height:1};b=null;var I=g.Yd("yt-html5-player-modules::subtitlesModuleData");I&&(b=new g.jM(I));this.storage=b;var u;this.Um=!((u=F.Qa())==null||!u.V8());this.D=ibm(this);this.WN=!this.D&&this.Jz&&this.Um&&(this.Z==="LIVE"||this.Z==="SABR_LIVE");g.k(this,this.oI);this.D?this.dD=this.qf=null:(this.qf=new g.n8(this.uW,void 0,this),g.k(this,this.qf),this.dD=new g.ty(this.uWD,2E3,this),
g.k(this,this.dD));g.k(this,this.kQ);g.Pp(this.player,this.V.element,4);g.k(this,this.V);this.D||this.kQ.B(F,"resize",this.RR);(this.Q2=g.Pu(this.rD)&&!g.mu()&&!this.G.isFullscreen()&&!this.D&&!this.WN)&&this.kQ.B(F,"resize",this.teN);this.kQ.B(F,"onPlaybackAudioChange",this.bkz);this.kQ.B(F,g.u6("captions"),function(w){J.onCueRangeEnter(w)});
this.kQ.B(F,g.wq("captions"),function(w){J.onCueRangeExit(w)});
this.nW&&this.kQ.B(F,"videodatachange",function(w,M){J.onVideoDataChange(w,M)});
zhe(this,ADb()||{});this.player.IC("onCaptionsModuleAvailable")},frb=function(F){if(F.rD.Um===1||F.videoData.HO===1||g.Nb(F.videoData,"yt:cc")==="alwayson")return!0;
if(F.videoData.captionTracks.length)var J=F.getAudioTrack().U;if(F.rD.Um===2){if(g.hP(F.rD))var b=NKW(F);else if(F.storage)try{b=F.storage.get("module-enabled")}catch(u){F.storage.remove("module-enabled")}else b=null;if(b!=null)return!!b}b=H5W(F.player.getAudioTrack(),g.hP(F.rD));var I=g.Nb(F.videoData,"yt:cc");if(lrL(F)===void 0){if(b==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return I?I==="on":!0;if(b==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return I==="on"}else return I==="on";return J==="ON"||
g.Nb(F.videoData,"yt:cc")==="on"},oC=function(F,J){if(F.U&&(J===void 0||!J)||!F.videoData.captionTracks.length)return!1;
F=F.getAudioTrack();return!!F.C||F.U==="FORCED_ON"},lrL=function(F){var J=void 0,b=g.Rg(g.Qe(),65);
if(g.hP(F.rD)&&b!=null){if(NKW(F)!=null)return!1;J=!b}return J},cZ=function(F,J){if(!F.C)return null;
if(F.N&&F.N.Z)return F.N.Z;J=Wbt(F,J);J=g.gA(F.C.U,J);var b=null;if(Lkb(F.rD)){var I=F.G.isInline()?void 0:g.S9("yt-player-caption-sticky-language");for(var u=[I,F.videoData.captionsLanguagePreference,F.rD.captionsLanguagePreference,g.Nb(F.videoData,"yt:cc_default_lang")],w=!1,M=0;M<u.length;M++){var q=u[M];if(q){w=!0;for(var v=0;v<J.length;v++)if(g.eE(J[v])===q)return J[v];for(v=0;v<J.length;v++)if(g.eE(J[v]).split("-")[0]===q.split("-")[0])return J[v]}}if(w&&F.C&&(u=F.C.D,u.length))for(u=g.N(u),
w=u.next();!w.done;w=u.next())if(w=w.value,w.languageCode===I){b=w;break}}else for(I=[F.videoData.captionsLanguagePreference,F.rD.captionsLanguagePreference,g.Nb(F.videoData,"yt:cc_default_lang")],u=0;u<I.length;u++)for(w=0;w<J.length;w++)if(g.eE(J[w])===I[u])return J[w];I=null;F.N&&F.N.T&&(I=F.N.T);I||(I=J.find(function(a){return a.isDefault})||null);
I||(I=J[0]||hK(F));I&&b&&g.eE(I).split("-")[0]!==b.languageCode.split("-")[0]&&(I=FDV(I,b));return I},hK=function(F){return F.N&&F.N.C},UM=function(F){var J=hK(F);
return!!J&&F.U===J},dIW=function(F,J){var b=F.G.Qa().Pb().textTracks;
F=F.U.toString();for(var I=0;I<b.length;I++){var u=b[I];u.id===F&&(J?u.mode!=="showing"&&(u.mode="showing"):u.mode==="showing"&&(u.mode="disabled"))}},tK=function(F,J,b){F.loaded&&F.unload();
b!=null&&(F.Y=b,F.Y&&(g.hP(F.rD)?xx(F,!!J):nZ(F,!!J)));F.rD.S("html5_report_caption_format_change")&&Eee(F,F.U,J,F.Y,!1);F.U=J;oC(F)&&(J=hK(F),F.rD.S("html5_report_caption_format_change")&&Eee(F,F.U,J,F.Y,!0),F.U=J);var I;jDL(F,(I=F.U)!=null?I:void 0);F.load()},VXL=function(F,J){if(J instanceof dp){var b=F.Gj[J.id];
b&&b.U!==J&&(b.dispose(),delete F.Gj[J.id],b=null);b||(b=GEL(F,J))&&(F.Gj[J.id]=b)}else b=J.windowId,F.KW[b]||(F.KW[b]=[]),F.KW[b].push(J)},GEL=function(F,J){var b=PBR(F);
if(!b)return null;var I=F.U?g.eE(F.U):null;I&&g.Mmb.test(I)&&(J.params.CF=1);var u=F.cN.getPlayerSize();I=u.height*F.eE.height;u=u.width*F.eE.width;F.rD.playerStyle!=="google-live"||F.T.isDefault||Object.assign(J.params,F.T);switch(J.params.Dd!=null?J.params.Dd:J.C.length>1?1:0){case 1:return new Yx(J,F.T,F.W,b.width,b.height,u,I,F.rD.experiments,F.uI.bind(F),F.G);case 2:return new RC(J,F.T,F.W,b.width,b.height,u,I,F.rD.experiments,F.uI.bind(F),F.G);default:return new KZ(J,F.T,F.W,b.width,b.height,
u,I,F.rD.experiments,F.uI.bind(F),F.G)}},zhe=function(F,J,b){b=b===void 0?!1:b;
var I=Z3.kH;F.T={};Object.assign(F.T,Z3);F.T.kH={};Object.assign(F.T.kH,I);F.W={kH:{}};var u=J.backgroundOverride?F.W:F.T,w=J.background||I.background;BZ.test(w);u.kH.background=w;u=J.colorOverride?F.W:F.T;w=J.color||I.color;BZ.test(w);u.kH.color=w;u=J.windowColorOverride?F.W:F.T;w=J.windowColor||Z3.windowColor;BZ.test(w);u.windowColor=w;u=J.backgroundOpacityOverride?F.W:F.T;w=J.backgroundOpacity;w==null&&(w=I.backgroundOpacity);u.kH.backgroundOpacity=w;u=J.fontSizeIncrementOverride?F.W:F.T;w=J.fontSizeIncrement;
w==null&&(w=I.fontSizeIncrement);u.kH.fontSizeIncrement=w;w=J.fontStyleOverride?F.W:F.T;u=J.fontStyle;u==null&&(u=I.bold&&I.italic?3:I.bold?1:I.italic?2:0);w=w.kH;switch(u){case 1:w.bold=!0;delete w.italic;break;case 2:delete w.bold;w.italic=!0;break;case 3:w.bold=!0;w.italic=!0;break;default:delete w.bold,delete w.italic}u=J.textOpacityOverride?F.W:F.T;w=J.textOpacity;w==null&&(w=I.textOpacity);u.kH.textOpacity=w;u=J.windowOpacityOverride?F.W:F.T;w=J.windowOpacity;w==null&&(w=Z3.windowOpacity);u.windowOpacity=
w;u=J.charEdgeStyleOverride?F.W:F.T;w=J.charEdgeStyle;w==null&&(w=I.charEdgeStyle);u.kH.charEdgeStyle=w;u=J.fontFamilyOverride?F.W:F.T;w=J.fontFamily;w==null&&(w=I.fontFamily);u.kH.fontFamily=w;F.loaded&&F.RR();b&&g.rm("yt-player-caption-display-settings",J,2592E3)},BKb=function(F,J){if(!F.C)return{};
if(J){F.rD.S("html5_report_caption_format_intent")&&!g.Vj(J)&&F.IQ(J.vss_id,"m");if(F.D||!g.Um(J))return;if(g.Vj(J)){tK(F,null,!0);return}for(var b,I=g.gA(F.C.U,!0),u=0;u<I.length;u++){var w=I[u];w.languageCode!==J.languageCode||b&&(w.languageName!==J.languageName||(w.captionId||"")!==(J.captionId||"")||g.vC(w)!==J.displayName)||(b=J.translationLanguage?FDV(w,J.translationLanguage):w)}F.po(J.position);!b||b===F.U&&F.loaded||(J=g.Ca(),I=g.eE(b),J.length&&I===J[J.length-1]||(J.push(I),g.rm("yt-player-caption-language-preferences",
J)),Lkb(F.rD)&&!F.G.isInline()&&g.rm("yt-player-caption-sticky-language",I,2592E3),tK(F,b,!0))}else return F.loaded&&F.U&&!UM(F)?g.aH(F.U):{};return""},r61=function(F,J,b){J&&!F.Tj?(J=UDL({CF:0,
lang:"en"}),F.Tj=[J,new fZ(J.start,J.end-J.start,0,J.id,b!=null?b:"Captions look like this")],F.player.TU(F.Tj)):!J&&F.Tj&&(TK1(F,F.Tj),F.Tj=null)},TK1=function(F,J){F.player.L4(J);
J=g.N(J);for(var b=J.next();!b.done;b=J.next())g.Hk(F.fW,b.value);vZ(F.qf)},jDL=function(F,J){F.rD.S("html5_modify_caption_vss_logging")&&(F.videoData.UK=J)},PBR=function(F){var J=F.cN.getVideoContentRect(!0).height,b=F.cN.getVideoContentRect(!0).width;
if(!J||!b)return null;J*=F.eE.height;b*=F.eE.width;return{width:b,height:J}},nZ=function(F,J){if(F.storage)try{F.storage.set("module-enabled",J)}catch(b){}},xx=function(F,J){F.G.isInline()||g.rm("yt-player-sticky-caption",J,2592E3)},NKW=function(F){if(!F.G.isInline())return g.S9("yt-player-sticky-caption")},ibm=function(F){var J,b=!((J=F.G.Qa())==null||!J.HP());
return F.Jz&&b&&F.Z!=="LIVE"&&F.Z!=="SABR_LIVE"},Wbt=function(F,J){g.Xc(F.videoData)&&(J=!0);
J||(J=F.Z==="TTS"?!1:F.Z==="INNERTUBE"?!1:!0);return J||F.rD.S("web_deprecate_always_includes_asr_setting")&&g.hP(F.rD)?!0:!!g.Rg(g.Qe(),66)},Eee=function(F,J,b,I,u){u?F.XF(b,!0,"g"):I?J?F.XF(b,!!b,"m"):b&&F.XF(b,!0,"m"):!J&&b&&F.XF(b,!0,"s")};
g.PU.prototype.iP=g.IG(67,function(){return!1});
g.PU.prototype.Wl=g.IG(66,function(){});
g.BU.prototype.Wl=g.IG(65,function(F,J,b){var I=this;this.iR();J=this.UG(F,J);var u=this.SE.J().S("html5_report_captions_ctmp_qoe"),w=(0,g.jR)();this.zf();Z5b(this,J,{format:"RAW",onSuccess:function(M){I.C=null;if(u){var q=(M.responseText.length/1024).toFixed(),v=(0,g.jR)();I.videoData.UQ("capresp",{ms:v-w,kb:q})}b.b4(M.responseText,F)},
onError:u?function(M){var q;M=(q=M==null?void 0:M.status)!=null?q:0;I.videoData.UQ("capfail",{status:M})}:void 0,
withCredentials:!0})});
g.rA.prototype.Wl=g.IG(64,function(F,J,b){var I=this;this.iR();J=this.UG(F,J);this.zf();this.C=g.E6(J,{format:"RAW",onSuccess:function(u){I.C=null;b.b4(u.responseText,F)},
withCredentials:!0})});
g.A2.prototype.j7=g.IG(63,function(){for(var F=g.Oa(document,"track",void 0,this.C),J=0;J<F.length;J++)g.ID(F[J])});
g.Qw.prototype.j7=g.IG(62,function(){this.mediaElement.j7()});
g.A2.prototype.V8=g.IG(61,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.Qw.prototype.V8=g.IG(60,function(){return this.mediaElement.V8()});
g.A2.prototype.HP=g.IG(59,function(){return!!this.C.textTracks});
g.Qw.prototype.HP=g.IG(58,function(){return this.mediaElement.HP()});
g.A2.prototype.qN=g.IG(57,function(F){for(var J=0;J<F.length;J++)this.C.appendChild(F[J])});
g.Qw.prototype.qN=g.IG(56,function(F){this.mediaElement.qN(F)});
g.vg.prototype.M6=g.IG(51,function(F,J,b){this.xl.M6(F,J,b)});
g.x3.prototype.M6=g.IG(50,function(F,J,b){this.U.set(F,{VO:J,W$:b})});
g.n9.prototype.M6=g.IG(49,function(F,J,b){this.fW.M6(F,J,b)});
g.vg.prototype.dG=g.IG(48,function(F){return this.xl.dG(F)});
g.n9.prototype.dG=g.IG(47,function(F){var J=2;this.V.has(F)?J=0:g.XZk(this,F)&&(J=1);return J});
g.Hl.prototype.C=g.IG(46,function(F){g.Lc.apply(null,[5,this.tag,F].concat(g.W(g.Ba.apply(1,arguments))))});
g.ly.prototype.Z8=g.IG(43,function(F){var J=this.app.F4();return J?J.Z8(F):!1});
g.cg.prototype.Z8=g.IG(42,function(F){return this.Y4().some(function(J){return J.namespace===F})});
g.Ui.prototype.Z8=g.IG(41,function(F){return this.wD.f8.Z8(F)});
g.ly.prototype.IQ=g.IG(39,function(F,J){var b;(b=this.app.F_())==null||b.IQ(F,J)});
g.Pg.prototype.IQ=g.IG(38,function(F,J){F=[F,J];g.VT(this,g.dr(this.provider),"cfi",F)});
g.Oi.prototype.IQ=g.IG(37,function(F,J){this.qoe&&this.qoe.IQ(F,J)});
g.Ui.prototype.IQ=g.IG(36,function(F,J){this.wD.IQ(F,J)});
g.it.prototype.IQ=g.IG(35,function(F,J){this.zF().IQ(F,J)});
g.ly.prototype.XF=g.IG(34,function(F,J,b){var I;(I=this.app.F_())==null||I.XF(F,J,b)});
g.Pg.prototype.XF=g.IG(33,function(F,J,b){if(this.qf!==F||this.NW!==J)J=J==="rawcc"?"":J,b=[F,J,this.qf,b],g.VT(this,g.dr(this.provider),"cfs",b),this.qf=F,this.NW=J});
g.Oi.prototype.XF=g.IG(32,function(F,J,b){this.qoe&&this.qoe.XF(F,J,b)});
g.Ui.prototype.XF=g.IG(31,function(F,J,b){this.wD.XF(F,J,b)});
g.it.prototype.XF=g.IG(30,function(F,J,b){this.zF().XF(F,J,b)});
g.wr.prototype.jP=g.IG(19,function(){return this.Y});
g.Np.prototype.jP=g.IG(18,function(){var F;return((F=this.F_())==null?void 0:F.NP())||null});
g.ly.prototype.NP=g.IG(17,function(){return this.app.jP()});
g.Ui.prototype.NP=g.IG(16,function(){return this.wD.NP()});
g.it.prototype.NP=g.IG(15,function(){var F;return((F=this.Zv)==null?void 0:F.jP())||null});
g.ES.prototype.uf=g.IG(1,function(F){return(F=this.QB(F))?F.U:0});
g.Lo.prototype.uf=g.IG(0,function(){return 0});
var ulb=/#(.)(.)(.)/,I8U=/^#(?:[0-9a-f]{3}){1,2}$/i,KDH={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};aC.prototype.contains=function(F){F=g.AL(this.segments,F);return F>=0||F<0&&(-F-1)%2===1};
aC.prototype.length=function(){return this.segments.length/2};
g.z(vMR,g.R);g.A=vMR.prototype;g.A.X_=function(){g.R.prototype.X_.call(this);this.T&&this.T.cancel()};
g.A.hI=function(){this.seekTo(this.player.getCurrentTime())};
g.A.seekTo=function(F){F-=this.player.Xq();var J=this.C;this.C=g.ck(this.Tj.CA(F).aI);J!==this.C&&this.N&&this.N()};
g.A.reset=function(){this.Z=new aC;this.W=-1;this.T&&(this.T.cancel(),this.T=null)};
g.A.DI=function(){this.iR();var F;if(F=this.C!=null)F=this.C,F=F.C.D$(F);if(F&&!this.T&&!(this.C&&this.C.startTime-this.player.getCurrentTime()>30)){F=this.C;F=F.C.qc(F);var J=F.aI[0],b;if((b=this.player.getVideoData())==null?0:b.enableServerStitchedDai)if(b=this.player.NP()){var I=J.C.info.id,u=J.Mf,w=F.aI[0].hF;if(this.policy.fW){if(b=b.Rz(w,u,I,3))F.Z=b}else if(I=b.R9(w,u,I,3))if(b=b.dG(u),b===0)I&&(F.C=new g.yJ(I));else if(b===2){this.V.start();a8L(this)&&this.seekTo(this.player.getCurrentTime());
return}}J.C.index.vF(J.Mf)?(this.Z.contains(F.aI[0].Mf)||e68(this,F),this.C=g.ck(F.aI)):a8L(this)&&this.seekTo(this.player.getCurrentTime())}this.V.start()};
g.z(ex,g.PU);g.A=ex.prototype;g.A.Wl=function(F,J,b){var I=this;this.zf();J=gMW(this,F.getId());J||(J=F.languageCode,J=this.C.isManifestless?mDb(this,J,"386"):mDb(this,J));if(J){var u=(J.index.uf(J.index.nj())-J.index.getStartTime(J.index.nj()))*1E3,w=this.G.J(),M=new g.R04(w),q=function(){I.T&&I.T.reset();I.W=!0};
w.S("html5_keep_caption_data_after_seek")&&(q=null);this.T=new vMR(M,this.G,J,function(v,a){b.b4(v,F,a,u)},this.V||g.nF(J.info),q)}};
g.A.iP=function(){var F=this.W;this.W=!1;return F};
g.A.xW=function(F){var J=this.G.J().S("html5_fallback_if_rawcc_missing");var b=this.C.C.rawcc!=null;if(!this.V||!b&&J)J=this.C.isManifestless?p18(this,"386"):p18(this);else{if(!b){this.logger.C(386248249,"rawcc used but unavailable");return}J=[new g.qF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.qF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}J=g.N(J);
for(b=J.next();!b.done;b=J.next())g.Vl(this.U,b.value);F.L8()};
g.A.zf=function(){this.T&&(this.T.dispose(),this.T=null)};
g.A.UG=function(){return""};
g.A.VE=function(){this.T&&(this.T.reset(),this.G.Yo("captions"))};
var BZ=/^#(?:[0-9a-f]{3}){1,2}$/i;var z61=["left","right","center","justify"];g.z(KZ,g.U);g.A=KZ.prototype;g.A.HT=function(F,J){this.oI=F;this.nW=J;var b=g.NB(this.element,this.element.parentElement);this.bR=F-b.x;this.cN=J-b.y};
g.A.Sr=function(F,J){if(F!==this.oI||J!==this.nW){g.I3(this.element,"ytp-dragging")||g.uG(this.element,"ytp-dragging");var b=g.fL(this.element);F=F-this.bR-.02*this.playerWidth;var I=J-this.cN-.02*this.playerHeight,u=(F+b.width/2)/this.maxWidth*3;u=Math.floor(g.AD(u,0,2));var w=(I+b.height/2)/this.maxHeight*3;w=Math.floor(g.AD(w,0,2));J=u+w*3;F=(F+u/2*b.width)/this.maxWidth;F=g.AD(F,0,1)*100;b=(I+w/2*b.height)/this.maxHeight;b=g.AD(b,0,1)*100;this.U.params.qQ=J;this.U.params.h6=b;this.U.params.Fx=
F;this.U.params.isDefault=!1;this.C.qQ=J;this.C.h6=b;this.C.Fx=F;this.C.isDefault=!1;this.eE.qQ=J;this.eE.h6=b;this.eE.Fx=F;this.eE.isDefault=!1;this.B3()}};
g.A.Qy=function(){g.Mr(this.element,"ytp-dragging")};
g.A.B3=function(){this.RB(this.V)};
g.A.getType=function(){return this.type};
g.A.RB=function(F){var J=this.Um?0:Math.min(this.HX(),this.maxWidth),b=this.SO(),I=this.Um;if(I){var u=getComputedStyle(this.Z.parentNode);u=pZ(u.borderLeftWidth)+pZ(u.borderRightWidth)+pZ(u.paddingLeft)+pZ(u.paddingRight)}else u=0;var w=u;u="";this.U.params.CF===3&&(u="rotate(180deg)");var M=I?"calc(96% - "+w+"px)":"96%";g.aN(this.element,{top:0,left:0,right:"",bottom:"",width:J?J+"px":"",height:b?b+"px":"","max-width":M,"max-height":M,margin:"",transform:""});this.ZA(F);u={transform:u,top:"",left:"",
width:J?J+"px":"",height:b?b+"px":"","max-width":"","max-height":""};var q=this.C.Fx*.96+2;M=this.C.qQ;switch(M){case 0:case 3:case 6:(I=this.C.kH.fontSizeIncrement)&&I>0&&this.C.CF!==2&&this.C.CF!==3&&(q=Math.max(q/(1+I*2),2));u.left=q+"%";break;case 1:case 4:case 7:u.left=q+"%";q=this.Z.offsetWidth;J||q?(J=J||q+1,u.width=J+"px",u["margin-left"]=I?J/-2-w/2+"px":J/-2+"px"):u.transform+=" translateX(-50%)";break;case 2:case 5:case 8:u.right=100-q+"%"}I=this.C.h6*.96+2;switch(M){case 0:case 1:case 2:u.top=
I+"%";break;case 3:case 4:case 5:u.top=I+"%";(b=b||this.element.clientHeight)?(u.height=b+"px",u["margin-top"]=b/-2+"px"):u.transform+=" translateY(-50%)";break;case 6:case 7:case 8:u.bottom=100-I+"%"}g.aN(this.element,u);if(this.W){b=this.Z.offsetHeight;I=1;for(J=0;J<F.length;J++)u=F[J],typeof u.text==="string"&&(I+=u.text.split("\n").length-1,u.append||J===0||I++);b/=I;this.W.style.height=b+"px";this.W.style.width=b+"px";this.element.style.paddingLeft=b+5+"px";this.element.style.paddingRight=b+
5+"px";F=Number(this.element.style.marginLeft.replace("px",""))-b-5;b=Number(this.element.style.marginRight.replace("px",""))-b-5;this.element.style.marginLeft=F+"px";this.element.style.marginRight=b+"px"}};
g.A.ZA=function(F){var J;for(J=0;J<F.length&&F[J]===this.V[J];J++);if(this.WN||this.V.length>J)J=0,this.WN=!1,this.V=[],this.Y=this.qf=this.fW=null,g.J6(this.Z);for(;J<F.length;J++)dDV(this,F[J])};
g.A.HX=function(){return 0};
g.A.SO=function(){return 0};
g.A.toString=function(){return g.U.prototype.toString.call(this)};jf1.prototype.clear=function(){this.T=this.time=this.mode=0;this.C=[];this.reset()};
jf1.prototype.reset=function(){this.mode=0;this.Z.reset(0);this.D.reset(1)};
var Got=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];gp.prototype.set=function(F){this.type=F};
gp.prototype.get=function(){return this.type};
mn.prototype.clear=function(){this.state=0};
mn.prototype.update=function(){this.state=this.state===2?1:0};
mn.prototype.o8=function(){return this.state!==0};
mn.prototype.matches=function(F,J){return this.o8()&&F===this.Wm&&J===this.QQ};
rDk.prototype.reset=function(){this.timestamp=this.C=0};
yV.prototype.updateTime=function(F){for(var J=1;J<=15;++J)for(var b=1;b<=32;++b)this.T[J][b].timestamp=F};
yV.prototype.debugString=function(){for(var F="\n",J=1;J<=15;++J){for(var b=1;b<=32;++b){var I=this.T[J][b];F=I.C===0?F+"_":F+String.fromCharCode(I.C)}F+="\n"}return F};
yV.prototype.reset=function(F){for(var J=0;J<=15;J++)for(var b=0;b<=32;b++)this.T[J][b].reset();this.Z=F;this.C=0;this.U=this.row=1};
var Sat=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],sfL=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Yam=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],$DH=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];R6W.prototype.reset=function(F,J){this.D=J;this.style.set(2);this.U=this.W;this.Z=this.V;this.C=this.U;var b=(F<<2)+(J<<1);this.W.reset(b);this.V.reset(b);this.text.reset((F<<2)+(J<<1)+1)};
EMt.prototype.reset=function(F){this.D=F;this.U.clear();this.Z=this.T;this.T.reset(F,0);this.W.reset(F,1)};oMb.prototype.Z=function(){};g.z(fZ,g.b6);fZ.prototype.toString=function(){return g.b6.prototype.toString.call(this)};g.z(WZ,g.R);WZ.prototype.Ov=function(){return[]};
WZ.prototype.reset=function(){};g.z(dp,g.b6);dp.prototype.toString=function(){return g.b6.prototype.toString.call(this)};
var EM=0;g.z(jx,WZ);jx.prototype.reset=function(){this.W={};this.U=this.C=null;this.D=!0};
jx.prototype.Ov=function(F,J){F=F.firstChild;F.getAttribute("format");J=J||0;Number.isFinite(J);F=Array.from(F.childNodes);F=g.N(F);for(var b=F.next();!b.done;b=F.next())if(b=b.value,b.nodeType===1)switch(b.tagName){case "head":var I=b;break;case "body":var u=b}if(I)for(I=Array.from(I.childNodes),I=g.N(I),F=I.next();!F.done;F=I.next())if(F=F.value,F.nodeType===1)switch(F.tagName){case "pen":b=F.getAttribute("id");var w=this.pens,M={},q=F.getAttribute("p");q&&Object.assign(M,this.pens[q]);q=VV(F,"b");
q!=null&&(M.bold=q);q=VV(F,"i");q!=null&&(M.italic=q);q=VV(F,"u");q!=null&&(M.underline=q);q=PZ(F,"et");q!=null&&(M.charEdgeStyle=q);q=PZ(F,"of");q!=null&&(M.offset=q);q=TQ(F,"bc");q!=null&&(M.background=q);q=TQ(F,"ec");q!=null&&(M.QI=q);q=TQ(F,"fc");q!=null&&(M.color=q);q=PZ(F,"fs");q!=null&&q!==0&&(M.fontFamily=q);q=GQ(F,"sz");q!==void 0&&(M.fontSizeIncrement=q/100-1);q=GQ(F,"bo");q!==void 0&&(M.backgroundOpacity=q/255);q=GQ(F,"fo");q!==void 0&&(M.textOpacity=q/255);q=PZ(F,"rb");q!=null&&q!==10&&
q!==0&&(M.Eo=q>10?q-1:q);F=PZ(F,"hg");F!=null&&(M.Qn=F);w[b]=M;break;case "ws":b=F.getAttribute("id");this.Y[b]=xDk(this,F);break;case "wp":b=F.getAttribute("id"),this.V[b]=nM1(this,F)}if(u){I=[];u=Array.from(u.childNodes);u=g.N(u);for(F=u.next();!F.done;F=u.next())if(F=F.value,F.nodeType===1)switch(F.tagName){case "w":this.C=tqz(this,F,J,!1);(F=this.W[this.C.id])&&F.end>this.C.start&&(F.end=this.C.start);this.W[this.C.id]=this.C;I.push(this.C);break;case "p":var v=F;q=J;b=[];w=v.getAttribute("w")||
this.Z;M=!!VV(v,"a");q=(GQ(v,"t")||0)+q;var a=GQ(v,"d")||5E3;M||(!this.D&&this.U&&this.U.windowId===w&&this.U.end>q&&(this.U.end=q),this.U&&this.U.text==="\n"&&(this.U.text=""));var e=M?6:5,K=v.getAttribute("p");K=K?this.pens[K]:null;var p=Array.from(v.childNodes);p.length&&(this.D=v.getAttribute("d")!=null);for(v=0;v<p.length;v++){var m=p[v],y=void 0;v>0&&(M=!0);var f=void 0;m.nodeType===1&&(f=m);if(f&&f.tagName==="s"){if((m=(m=f.getAttribute("p"))?this.pens[m]:null)&&m.Eo&&(m.Eo===1?(m=p.slice(v,
v+4),m.length===4&&(y=cD1(q,a,w,M,e,m,this.pens),v+=3)):y=cD1(q,a,w,M,e,[f],this.pens)),!y){var d=f;y=q;f=a;m=w;var G=M,P=e,r=d.textContent?d.textContent:"",Q=d.getAttribute("p");Q=Q?this.pens[Q]:null;d=GQ(d,"t")||0;y=new fZ(y+d,f-d,P,m,r,G,Q)}}else y=new fZ(q,a,e,w,m.textContent||"",M,K);b.push(y);this.U=y}if(b.length>0)for(b[0].windowId===this.Z&&(this.C=tqz(this,F,J,!0),I.push(this.C)),F=g.N(b),b=F.next();!b.done;b=F.next())b=b.value,b.windowId=this.C.id,this.C.C.push(b),I.push(b)}J=I}else J=[];
return J};var SPt=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(rp,WZ);rp.prototype.reset=function(){this.U.clear()};
rp.prototype.Ov=function(F,J){var b=JSON.parse(F);if(!b)return[];if(b.pens){F=0;for(var I=g.N(b.pens),u=I.next();!u.done;u=I.next()){u=u.value;var w={},M=u.pParentId;M&&Object.assign(w,this.C.get(M));u.bAttr&&(w.bold=!0);u.iAttr&&(w.italic=!0);u.uAttr&&(w.underline=!0);M=u.ofOffset;M!=null&&(w.offset=M);u.szPenSize!==void 0&&(w.fontSizeIncrement=u.szPenSize/100-1);M=u.etEdgeType;M!=null&&(w.charEdgeStyle=M);u.ecEdgeColor!==void 0&&(w.QI=Sx(u.ecEdgeColor));M=u.fsFontStyle;M!=null&&M!==0&&(w.fontFamily=
M);u.fcForeColor!==void 0&&(w.color=Sx(u.fcForeColor));u.foForeAlpha!==void 0&&(w.textOpacity=u.foForeAlpha/255);u.bcBackColor!==void 0&&(w.background=Sx(u.bcBackColor));u.boBackAlpha!==void 0&&(w.backgroundOpacity=u.boBackAlpha/255);(M=u.rbRuby)&&M!==10&&(w.Eo=M>10?M-1:M,w.H5=SPt.get(w.Eo));u.hgHorizGroup&&(w.Qn=u.hgHorizGroup);this.C.set(F++,w)}}if(b.wsWinStyles)for(F=0,I=g.N(b.wsWinStyles),u=I.next();!u.done;u=I.next())u=u.value,w={},(M=u.wsParentId)?Object.assign(w,this.Z.get(M)):Object.assign(w,
this.D),u.mhModeHint!==void 0&&(w.Dd=u.mhModeHint),u.juJustifCode!==void 0&&(w.textAlign=u.juJustifCode),u.pdPrintDir!==void 0&&(w.CF=u.pdPrintDir),u.sdScrollDir!==void 0&&(w.cA=u.sdScrollDir),u.wfcWinFillColor!==void 0&&(w.windowColor=Sx(u.wfcWinFillColor)),u.wfoWinFillAlpha!==void 0&&(w.windowOpacity=u.wfoWinFillAlpha/255),this.Z.set(F++,w);if(b.wpWinPositions)for(F=0,I=g.N(b.wpWinPositions),u=I.next();!u.done;u=I.next())u=u.value,w={},(M=u.wpParentId)&&Object.assign(w,this.T.get(M)),u.ahHorPos!==
void 0&&(w.Fx=u.ahHorPos),u.apPoint!==void 0&&(w.qQ=u.apPoint),u.avVerPos!==void 0&&(w.h6=u.avVerPos),u.ccCols!==void 0&&(w.VQ=u.ccCols),u.rcRows!==void 0&&(w.pA=u.rcRows),this.T.set(F++,w);if(b.events){F=[];b=g.N(b.events);for(I=b.next();!I.done;I=b.next()){var q=I.value;u=(q.tStartMs||0)+J;w=q.dDurationMs||0;if(q.id)M=String(q.id),I=Z$e(this,q,u,w,M),F.push(I),this.U.set(M,I);else{q.wWinId?M=q.wWinId.toString():(M="_"+EM++,I=Z$e(this,q,u,w,M),F.push(I),this.U.set(M,I));I=F;var v=q;w===0&&(w=5E3);
q=this.U.get(M);var a=!!v.aAppend,e=a?6:5,K=v.segs,p=null;v.pPenId&&(p=this.C.get(v.pPenId));for(v=0;v<K.length;v++){var m=K[v],y=m.utf8;if(y){var f=m.tOffsetMs||0,d=null;m.pPenId&&(d=this.C.get(m.pPenId));if((q.params.Dd!=null?q.params.Dd:q.C.length>1?1:0)===2&&a&&y==="\n")continue;m=null;var G=[],P;if(P=d&&d.Eo===1){P=K;var r=v;if(r+3>=P.length||!P[r+1].pPenId||!P[r+2].pPenId||!P[r+3].pPenId)P=!1;else{var Q=P[r+1].pPenId;(Q=this.C.get(Q))&&Q.Eo&&Q.Eo===2?(Q=P[r+2].pPenId,Q=this.C.get(Q),!Q||!Q.Eo||
Q.Eo<3?P=!1:(Q=P[r+3].pPenId,P=(Q=this.C.get(Q))&&Q.Eo&&Q.Eo===2?!0:!1)):P=!1}}if(P)f=K[v+1].utf8,m=K[v+3].utf8,P=K[v+2].utf8,r=this.C.get(K[v+2].pPenId),y=h6W(y,f,P,m,r),m=new fZ(u,w,e,M,y,a,d),v+=3;else{if(y.indexOf("<")>-1){var D=void 0;G=d;P=p;r=u;Q=w;var t=f,n=e,uk=a,AJ=[],F7=g.xv("<html>"+y+"</html>");if(!F7.getElementsByTagName("parsererror").length&&((D=F7.firstChild)==null?0:D.childNodes.length))for(D=g.N(F7.firstChild.childNodes),F7=D.next();!F7.done;F7=D.next()){F7=F7.value;var h=void 0,
L=void 0,l=(L=(h=F7.textContent)==null?void 0:h.replace(/\n/g,""))!=null?L:"";if(F7.nodeType!==3||l&&l.match(/^ *$/)==null){h={};Object.assign(h,G||P);L=void 0;switch((L=F7)==null?void 0:L.tagName){case "b":h.bold=!0;break;case "i":h.italic=!0;break;case "u":h.underline=!0}AJ.push(new fZ(r+t,Q-t,n,q.id,l,uk,h))}}G=AJ}G.length||(G=[new fZ(u+f,w-f,e,q.id,y,a,d||p)])}if(G.length)for(a=g.N(G),d=a.next();!d.done;d=a.next())d=d.value,I.push(d),q.C.push(d);else m&&(I.push(m),q.C.push(m))}a=!0}}}J=F}else J=
[];return J};g.z(sM,g.PU);sM.prototype.Wl=function(F,J,b){b$b(this.videoData.videoId,F.vssId,b.b4)};
sM.prototype.xW=function(F){if(this.audioTrack)for(var J=g.N(this.audioTrack.captionTracks),b=J.next();!b.done;b=J.next())g.Vl(this.U,b.value);F.L8()};g.z(Yx,KZ);Yx.prototype.ZA=function(F){var J=this.U.C;KZ.prototype.ZA.call(this,F);for(F=F.length;F<J.length;F++){var b=J[F];if(w&&b.C===u)var I=w;else{I={};Object.assign(I,b.C);Object.assign(I,sDe);var u=b.C;var w=I}dDV(this,b,I)}};
var sDe={dfQ:!0};g.z($x,oMb);$x.prototype.Z=function(F,J,b,I,u){if(b<I){var w="_"+EM++;b=b/1E3-this.W;I=I/1E3-this.W;F=new dp(b,I-b,5,w,{textAlign:0,qQ:0,Fx:J*2.5,h6:F*5.33});u=new fZ(b,I-b,5,w,u);this.U.push(F);this.U.push(u)}};
g.z(QV,WZ);QV.prototype.Ov=function(F){F=new $x(F,F.byteLength,this.U);if(H$b(F)){for(;F.byteOffset<F.C.byteLength;)for(F.version===0?F.T=X3(F)*(1E3/45):F.version===1&&(F.T=X3(F)*4294967296+X3(F)),F.D=CZ(F);F.D>0;F.D--){var J=CZ(F),b=CZ(F),I=CZ(F);J&4&&(J&3)===this.track&&(this.track===0||this.track===1)&&(J=this.C,J.C.push({time:F.T,type:this.track,O$:b,Dx:I,order:J.C.length}))}Tle(this.C,F);return F.U}return[]};
QV.prototype.reset=function(){this.C.clear()};g.z(RC,KZ);g.A=RC.prototype;g.A.B3=function(){g.HQ(this.KW)};
g.A.d0j=function(){g.Mr(this.element,"ytp-rollup-mode");this.RB(this.Kk,!0)};
g.A.SO=function(){return this.T?this.Tj:this.N};
g.A.HX=function(){return this.T?this.N:this.Tj};
g.A.RB=function(F,J){this.Kk=F;if(this.U.params.pA){for(var b=0,I=0;I<this.V.length&&b<F.length;I++)this.V[I]===F[b]&&b++;b>0&&b<F.length&&(F=this.V.concat(F.slice(b)));this.Om=this.Tj;this.N=this.Tj=0;KZ.prototype.RB.call(this,F);bbk(this,J)}KZ.prototype.RB.call(this,F)};IrV.prototype.unload=function(){this.Yc!=null&&(this.G.removeEventListener("sabrCaptionsDataLoaded",this.Yc),this.Yc=null);this.Ym=[];this.G.publish("sabrCaptionsBufferedRangesUpdated",this.Ym)};
IrV.prototype.K5=function(F){return{formatId:g.H4(F.info.C.info,this.MW),Mf:F.info.Mf+(this.MW?0:1),startTimeMs:F.info.hF*1E3,durationMs:F.info.W*1E3}};g.z(A6U,g.PU);g.A=A6U.prototype;g.A.Wl=function(F,J,b){this.zf();J=F.getId();J=J!=null&&J in this.C.C?this.C.C[J]:null;J||(J=F.languageCode,J=this.C.isManifestless?ve8(this,J,"386"):ve8(this,J));J&&(this.T=F,this.W=J,MXR(this.V,b),this.G.publish("sabrCaptionsTrackChanged",g.H4(J.info,this.C.MW)))};
g.A.xW=function(F){var J=this.C.isManifestless?qP8(this,"386"):qP8(this);J=g.N(J);for(var b=J.next();!b.done;b=J.next())g.Vl(this.U,b.value);F.L8()};
g.A.zf=function(){this.T&&(this.T=this.W=null,this.V.unload(),this.G.publish("sabrCaptionsTrackChanged",null))};
g.A.UG=function(){return""};
g.A.VE=function(){this.G.Yo("captions")};g.z(D3,WZ);
D3.prototype.Ov=function(F,J){var b=[];F=F.split(YPt);for(var I=1;I<F.length;I++){var u=F[I],w=J;if(u!==""&&!$It.test(u)){var M=CBR.exec(u);if(M&&M.length>=4){var q=Kb1(M[1]),v=Kb1(M[2])-q;q+=w;var a=(M=M[3])?M.split(" "):[];M={};var e=null;var K="";var p=null,m="";a=g.N(a);for(var y=a.next();!y.done;y=a.next())if(y=y.value.split(":"),y.length===2){var f=y[1];switch(y[0]){case "line":y=f.split(",");y[0].endsWith("%")&&(e=y[0],M.h6=Number.parseInt(e,10),y.length===2&&(K=y[1].trim()));break;case "position":y=
f.split(",");p=y[0];M.Fx=Number.parseInt(p,10);y.length===2&&(m=y[1].trim());break;case "align":switch(f){case "start":M.textAlign=0;break;case "middle":M.textAlign=2;break;case "end":M.textAlign=1}}}e||K||(K="end");if(!p)switch(M.textAlign){case 0:M.Fx=0;break;case 1:M.Fx=100;break;case 2:M.Fx=50}if(M.textAlign!=null){e=0;switch(K){case "center":e+=3;break;case "end":e+=6;break;default:e+=0}switch(m){case "line-left":e+=0;break;case "center":e+=1;break;case "line-right":e+=2;break;default:switch(M.textAlign){case 0:e+=
0;break;case 2:e+=1;break;case 1:e+=2}}K=e<0||e>8?7:e;M.qQ=K}u=u.substring(CBR.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");m=M;M=u;u={};if(M.indexOf("<")<0&&M.indexOf("&")<0)w=pzb(q,v,5,m),v=new fZ(q,v,5,w.id,M,!1,g.Vj(u)?void 0:u),b.push(w),b.push(v),w.C.push(v);else for(K=M.split(Xzb),K.length===1?(M=5,m=pzb(q,v,M,m)):(e=M=6,m=Object.assign({VQ:32},m),m=new dp(q,v,e,"_"+EM++,m)),b.push(m),e=q,p=0;p<K.length;p++)a=K[p],p%2===0?(y=g.xv("<html>"+a+"</html>"),y.getElementsByTagName("parsererror").length?
(f=y.createElement("span"),f.appendChild(y.createTextNode(a))):f=y.firstChild,eh8(this,e,v-(e-q),M,m,p>0,f,u,b)):e=Kb1(a)+w}CBR.lastIndex=0}}return b};
var $It=/^NOTE/,YPt=/(?:\r\n|\r|\n){2,}/,CBR=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Xzb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.RQ.xw(D3,{Ov:"wvppt"});g.z(kx,g.R);
kx.prototype.Ov=function(F,J,b,I){I=I||0;b=mIV(this,F,b||0);F=[];try{for(var u=g.N(b),w=u.next();!w.done;w=u.next()){var M=w.value,q=M.trackData,v=M.y0;if(typeof q!=="string"){b=F;var a=b.concat,e=J,K=q,p=v,m=I;if(!LDk(K))throw Error("Invalid binary caption track data");this.C||(this.C=new QV(m,e));var y=this.C.Ov(K,p);var f=a.call(b,y)}else{if(q.substring(0,6)==="WEBVTT"){b=F;var d=b.concat;this.C||(this.C=new D3);var G=this.C.Ov(q,v);Math.random()<.01&&g.rQ(Error("Deprecated subtitles format in web player: WebVTT"));var P=
d.call(b,G)}else{b=F;var r=b.concat;a:{e=J;if(q[0]==="{")try{this.C||(this.C=new rp(y6k(e)));var Q=this.C.Ov(q,v);break a}catch(F7){g.Td(F7);Q=[];break a}var D=g.xv(q);if(!D||!D.firstChild){var t=Error("Invalid caption track data");t.params=q;throw t;}if(D.firstChild.tagName==="timedtext"){if(Number(D.firstChild.getAttribute("format"))===3){K=D;this.C||(this.C=new jx(y6k(e),this.rD));Q=this.C.Ov(K,v);break a}var n=Error("Unsupported subtitles format in web player (Format2)");n.params=q;throw n;}if(D.firstChild.tagName===
"transcript"){var uk=Error("Unsupported subtitles format in web player (Format1)");uk.params=q;throw uk;}var AJ=Error("Invalid caption track data");AJ.params=q;throw AJ;}P=r.call(b,Q)}f=P}F=f}return F}catch(F7){return this.logger.C(187101178,"Captions parsing failed: "+F7.message+". "),this.clear(),[]}};
kx.prototype.clear=function(){this.C&&this.C.dispose();this.C=null};
kx.prototype.reset=function(){this.C&&this.C.reset()};
kx.prototype.X_=function(){g.R.prototype.X_.call(this);this.clear()};var Z3={windowColor:"#080808",windowOpacity:0,textAlign:2,qQ:7,Fx:50,h6:100,isDefault:!0,kH:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(OM,g.GN);g.A=OM.prototype;g.A.X_=function(){if(this.D||this.WN){var F=this.G.Qa();F&&!F.iR()&&F.j7()}else r61(this,!1);g.GN.prototype.X_.call(this)};
g.A.S0=function(){return this.rD.S("html5_honor_caption_availabilities_in_audio_track")&&this.Z!=="LIVE"&&this.Z!=="SABR_LIVE"};
g.A.X$=function(){if(this.Jz)return this.D||this.WN;var F=this.getAudioTrack();if(this.S0()){if(!F.captionTracks.length)return!1;if(!this.C)return!0}F=H5W(F,g.hP(this.rD));return F==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:F==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?oC(this):lrL(this)||oC(this)?!0:frb(this)};
g.A.load=function(){g.GN.prototype.load.call(this);this.N=this.getAudioTrack();if(this.C)this.U&&(this.oI.clear(),this.D?dIW(this,!0):this.player.getPresentingPlayerType()!==3&&this.C.Wl(this.U,"json3",this.Om),this.D||this.WN||UM(this)||this.player.IC("captionschanged",g.aH(this.U)));else{var F;this.Z==="OFFLINE"?F=new sM(this.player,this.videoData,this.getAudioTrack()):this.Z==="SABR_LIVE"?F=new A6U(this.videoData.C,this.player):this.Z==="LIVE"?F=new ex(this.videoData.C,this.player):this.Z==="INNERTUBE"?
F=new g.BU(this.player,this.videoData,this.getAudioTrack()):F=new g.rA(this.player,this.videoData.zU,this.videoData.videoId,g.aXG(this.videoData),this.videoData.OM,this.videoData.eventId);this.C=F;g.k(this,this.C);this.C.xW(this.Om)}};
g.A.unload=function(){this.D&&this.U?dIW(this,!1):(this.dD&&g.L8(this.dD),this.player.Yo("captions"),this.fW=[],this.C&&this.C.zf(),this.oI.clear(),this.Tj&&this.player.TU(this.Tj),this.RR());g.GN.prototype.unload.call(this);this.player.B5();this.player.IC("captionschanged",{})};
g.A.create=function(){this.X$()&&this.load();var F;a:{var J,b,I;if(this.rD.S("web_player_nitrate_promo_tooltip")&&((J=this.videoData.getPlayerResponse())==null?0:(b=J.captions)==null?0:(I=b.playerCaptionsTracklistRenderer)==null?0:I.enableTouchCaptionsNitrate)){var u,w;if(J=(F=this.videoData.getPlayerResponse())==null?void 0:(u=F.captions)==null?void 0:(w=u.playerCaptionsTracklistRenderer)==null?void 0:w.captionTracks)for(F=g.N(J),u=F.next();!u.done;u=F.next())if(u=u.value,u.kind==="asr"&&u.languageCode===
"en"){F=!0;break a}}F=!1}F&&this.G.publish("showpromotooltip",this.V.element)};
g.A.L8=function(){var F=H5W(this.player.getAudioTrack(),g.hP(this.rD));var J=F==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?cZ(this,this.Y):F==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&oC(this)?hK(this):lrL(this)||this.Y||frb(this)?cZ(this,this.Y):oC(this)?hK(this):null;if(this.D||this.WN){var b=g.gA(this.C.U,!0);F=[];for(var I=0;I<b.length;I++){var u=b[I],w=g.H1("TRACK");w.setAttribute("kind","subtitles");w.setAttribute("label",g.vC(u));w.setAttribute("srclang",g.eE(u));w.setAttribute("id",u.toString());
this.WN||w.setAttribute("src",this.C.UG(u,"vtt"));u===J&&w.setAttribute("default","1");F.push(w)}J=this.G.Qa();J.qN(F);F=J.Pb();this.Um&&this.kQ.B(F.textTracks,"change",this.sH_)}else!this.U&&J&&tK(this,J),this.player.IC("onCaptionsTrackListChanged"),this.player.SZ("onApiChange")};
g.A.sH_=function(){for(var F=this.G.Qa().Pb().textTracks,J=null,b=0;b<F.length;b++)if(F[b].mode==="showing")a:{J=g.gA(this.C.U,!0);for(var I=0;I<J.length;I++)if(J[I].toString()===F[b].id){J=J[I];break a}J=null}(this.loaded?this.U:null)!==J&&tK(this,J,!0)};
g.A.JXG=function(){!this.U&&this.D||this.unload()};
g.A.b4=function(F,J,b,I){if(F){var u;jDL(this,(u=this.U)!=null?u:void 0);this.C.iP()&&(this.fW=[],this.G.Yo("captions"),vZ(this.qf),this.oI.reset());if(this.videoData.xo){var w;b=((w=b)!=null?w:0)+this.videoData.xo}F=this.oI.Ov(F,J,b,I);if(this.nW)for(J=g.N(F),b=J.next();!b.done;b=J.next())b=b.value,b.T=this.videoData.clientPlaybackNonce,b.ac=this.videoData.xo;J=!this.rD.S("html5_keep_caption_data_after_seek")&&(this.Z==="LIVE"||this.Z==="SABR_LIVE");this.player.TU(F,void 0,J);!this.Y||this.WN||UM(this)||
g.jB(this.rD)||g.TB(this.rD)||g.sV(this.rD)||this.rD.WN==="shortspage"||this.player.isInline()||(g.L8(this.dD),F=UDL({qQ:0,Fx:5,h6:5,pA:2,textAlign:0,CF:0,lang:"en"}),this.zj=[F],J=["Click "," for settings"],this.bR||(b=new g.Mc(g.Ej()),g.k(this,b),this.bR=b.element),b=F.end-F.start,(I=g.vC(this.U))&&this.zj.push(new fZ(F.start,b,0,F.id,I)),this.zj.push(new fZ(F.start,b,0,F.id,J[0]),new fZ(F.start,b,0,F.id,this.bR,!0),new fZ(F.start,b,0,F.id,J[1],!0)),this.player.TU(this.zj),g.Z_(this.dD));!this.Y||
this.WN||UM(this)||(g.hP(this.rD)?xx(this,!0):nZ(this,!0),this.N&&(this.N.Z=this.U),this.player.B5());this.Y=!1}};
g.A.onCueRangeEnter=function(F){this.fW.push(F);vZ(this.qf)};
g.A.onCueRangeExit=function(F){g.Hk(this.fW,F);this.C instanceof ex&&this.C.V&&this.player.L4([F]);vZ(this.qf)};
g.A.getCaptionWindowContainerId=function(){return this.V.element.id};
g.A.uWD=function(){TK1(this,this.zj);this.zj=null};
g.A.uW=function(){var F=this;if(!this.Q2||!this.D){this.qf.stop();g.c_a(this.KW);this.fW.sort(g.IV);var J=this.fW;if(this.Tj){var b=g.qN(J,function(w){return this.Tj.indexOf(w)===-1},this);
b.length&&(J=b)}J=g.N(J);for(b=J.next();!b.done;b=J.next())VXL(this,b.value);J=g.N(Object.entries(this.Gj));var I=J.next();for(b={};!I.done;b={FL:void 0,ZQ:void 0},I=J.next()){var u=g.N(I.value);I=u.next().value;u=u.next().value;b.FL=I;b.ZQ=u;this.KW[b.FL]?(b.ZQ.element.parentNode||(b.ZQ instanceof RC||b.ZQ instanceof Yx||g.le(this.Gj,function(w){return function(M,q){q!==w.FL&&M.U.params.qQ===w.ZQ.U.params.qQ&&M.U.params.Fx===w.ZQ.U.params.Fx&&M.U.params.h6===w.ZQ.U.params.h6&&(M.dispose(),delete F.Gj[q]);
return q===w.FL}}(b),this),this.V.element.appendChild(b.ZQ.element)),b.ZQ.RB(this.KW[b.FL])):(b.ZQ.dispose(),delete this.Gj[b.FL])}}};
g.A.WuN=function(){zhe(this,{},!0);this.player.IC("captionssettingschanged")};
g.A.KR=function(){var F=Z3.kH;F={background:F.background,backgroundOpacity:F.backgroundOpacity,charEdgeStyle:F.charEdgeStyle,color:F.color,fontFamily:F.fontFamily,fontSizeIncrement:F.fontSizeIncrement,fontStyle:F.bold&&F.italic?3:F.bold?1:F.italic?2:0,textOpacity:F.textOpacity,windowColor:Z3.windowColor,windowOpacity:Z3.windowOpacity};var J=ADb()||{};J.background!=null&&(F.background=J.background);J.backgroundOverride!=null&&(F.backgroundOverride=J.backgroundOverride);J.backgroundOpacity!=null&&(F.backgroundOpacity=
J.backgroundOpacity);J.backgroundOpacityOverride!=null&&(F.backgroundOpacityOverride=J.backgroundOpacityOverride);J.charEdgeStyle!=null&&(F.charEdgeStyle=J.charEdgeStyle);J.charEdgeStyleOverride!=null&&(F.charEdgeStyleOverride=J.charEdgeStyleOverride);J.color!=null&&(F.color=J.color);J.colorOverride!=null&&(F.colorOverride=J.colorOverride);J.fontFamily!=null&&(F.fontFamily=J.fontFamily);J.fontFamilyOverride!=null&&(F.fontFamilyOverride=J.fontFamilyOverride);J.fontSizeIncrement!=null&&(F.fontSizeIncrement=
J.fontSizeIncrement);J.fontSizeIncrementOverride!=null&&(F.fontSizeIncrementOverride=J.fontSizeIncrementOverride);J.fontStyle!=null&&(F.fontStyle=J.fontStyle);J.fontStyleOverride!=null&&(F.fontStyleOverride=J.fontStyleOverride);J.textOpacity!=null&&(F.textOpacity=J.textOpacity);J.textOpacityOverride!=null&&(F.textOpacityOverride=J.textOpacityOverride);J.windowColor!=null&&(F.windowColor=J.windowColor);J.windowColorOverride!=null&&(F.windowColorOverride=J.windowColorOverride);J.windowOpacity!=null&&
(F.windowOpacity=J.windowOpacity);J.windowOpacityOverride!=null&&(F.windowOpacityOverride=J.windowOpacityOverride);return F};
g.A.Dr=function(F,J){var b={};Object.assign(b,ADb());Object.assign(b,F);zhe(this,b,J);this.player.IC("captionssettingschanged")};
g.A.RR=function(){!this.D&&this.loaded&&(g.ie(this.Gj,function(F,J){F.dispose();delete this.Gj[J]},this),this.uW())};
g.A.qJ=function(F,J){switch(F){case "fontSize":if(isNaN(J))break;F=g.AD(J,-2,4);this.Dr({fontSizeIncrement:F});return F;case "reload":J&&!this.D&&tK(this,this.U,!0);break;case "stickyLoading":J!==void 0&&this.rD.V&&(g.hP(this.rD)?xx(this,!!J):nZ(this,!!J));break;case "track":return BKb(this,J);case "tracklist":return this.C?g.EG(g.gA(this.C.U,!(!J||!J.includeAsr)),function(b){return g.aH(b)}):[];
case "translationLanguages":return this.C?this.C.D.map(function(b){return Object.assign({},b)}):[];
case "sampleSubtitles":this.D||J===void 0||r61(this,!!J);break;case "sampleSubtitlesCustomized":this.D||r61(this,!!J,J);break;case "recommendedTranslationLanguages":return g.Ca();case "defaultTranslationSourceTrackIndices":return this.C?this.C.Y:[]}};
g.A.getOptions=function(){var F="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.rD.V&&F.push("stickyLoading");return F};
g.A.w$=function(){var F=this.U;if(this.G.Z8("captions")){if(this.rD.S("html5_modify_caption_vss_logging")){var J;return(F=(J=this.videoData.UK)!=null?J:null)?{cc:g.Pgk(F)}:{}}if(F)return J=F.vssId,F.translationLanguage&&J&&(J="t"+J+"."+g.eE(F)),{cc:J}}return{}};
g.A.QuG=function(){this.isSubtitlesOn()?(g.hP(this.rD)?xx(this,!1):nZ(this,!1),jDL(this),this.rD.S("html5_report_caption_format_change")?tK(this,null,!0):(this.unload(),oC(this,!0)&&tK(this,hK(this),!1))):this.b$()};
g.A.b$=function(){var F=UM(this)||!this.U?cZ(this,!0):this.U;this.rD.S("html5_report_caption_format_intent")&&F&&this.IQ(F.vssId,"m");this.isSubtitlesOn()||tK(this,UM(this)||!this.U?cZ(this,!0):this.U,!0)};
g.A.isSubtitlesOn=function(){return!!this.loaded&&!!this.U&&!UM(this)};
g.A.bkz=function(){var F=UM(this);oC(this,F)?tK(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.S0()&&(this.Y=!1,this.U=null,this.C&&(this.C.dispose(),this.C=null)),this.X$()&&(F?tK(this,cZ(this,!1),!1):this.load()))};
g.A.po=function(F){F&&(this.eE={top:F.top,right:F.right,bottom:F.bottom,left:F.left,width:1-F.left-F.right,height:1-F.top-F.bottom},this.V.element.style.top=this.eE.top*100+"%",this.V.element.style.left=this.eE.left*100+"%",this.V.element.style.width=this.eE.width*100+"%",this.V.element.style.height=this.eE.height*100+"%",this.V.element.style.position="absolute",F=PBR(this))&&(this.V.element.style.width=F.width+"px",this.V.element.style.height=F.height+"px")};
g.A.onVideoDataChange=function(F,J){F==="newdata"&&(this.videoData=J,this.loaded&&this.unload(),this.Y=!1,this.U=null,this.C&&(this.C.dispose(),this.C=null,this.player.IC("captionschanged",{})),this.X$()&&this.load())};
g.A.getAudioTrack=function(){return this.nW&&this.player.getPresentingPlayerType()===2?this.videoData.eB:this.player.getAudioTrack()};
g.A.teN=function(){var F=this.G.Qa();F&&!F.iR()&&F.j7();this.G.isFullscreen()?(this.D=this.Jz=!0,this.loaded&&this.L8()):(this.Jz=this.rD.controlsType==="3",this.D=ibm(this));tK(this,this.U)};
g.A.uI=function(){var F,J,b,I=(F=this.videoData.getPlayerResponse())==null?void 0:(J=F.captions)==null?void 0:(b=J.playerCaptionsTracklistRenderer)==null?void 0:b.openTranscriptCommand;I&&this.player.jE("innertubeCommand",I)};
g.A.XF=function(F,J,b){var I=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,u="";F&&(u=F.vssId,u=u.replace(I,""));var w="";F&&F.getId()&&(w=F.getId()||"");F&&F.getXtags()&&(F=F.getXtags(),F=F.replace(I,""),w=w.concat(";"+F));this.G.XF(J?u:"",J?w:"",b)};
g.A.IQ=function(F,J){F=(F||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");F.length>0&&this.G.IQ(F,J)};
g.A.VE=function(){this.C&&this.C.VE()};
g.RQ.xw(OM,{uW:"smucd"});g.jn("captions",OM);})(_yt_player);
